### ISSUE TITLE
Vaccination details data is incomplete, inconsistent and incorrect

### ISSUE THREAD

**Issue by marcokrikke** [minvws/nl-covid19-coronacheck-app-ios#44]
### Describe the bug, issue or concern

I've received two vaccinations via GGD and see them twice in the app (RIVM + GGD).

When comparing the vaccination details with coronacheck.nl, data seems to be missing or inconsistent in the iOS app. Also within the app, data is incosistent between the vaccination details and the International QR Code details.

- GGD: 2nd dose in app mentions 'no' with last doses, while it is. The 'no' is confusing, it might lead to users believing their QR code is invalid. RIVM one mentions 'unknown', which is slightly better. The international QR code does say 2/2 doses
- RIVM vaccine manufacturer and type mentioned in the app, but not on coronacheck.nl
- RIVM certificate identifier does not match, but seems to be different every time I try, both on the website and in the app? Probably regenerated on every request, not sure.

### To Reproduce

1. Get fully vaccinated
2. Check if vaccinations are listed when adding a vaccination certificate
3. Check details of vaccinations
4. Create a QR code and check if it says 2/2 doses
5. Log in to https://coronacheck.nl/nl/print/
6. Check if vaccinations are listed when creating a vaccination certificate for priting
7. Check details of vaccinations, compare with (3)

### Expected behavior

- 'last dose' should say 'yes' when the vaccination is the final one required
- Information on coronacheck.nl and the CoronaCheck app should be presented in a consistent manner, i.e. same details on both channels.

### GGD

App: 
![GGD iOS app](https://user-images.githubusercontent.com/1352315/126960736-9941de0f-ac04-41bd-a96e-eea5a5c5e6cb.jpg)

Website:
![GGD coronacheck.nl](https://user-images.githubusercontent.com/1352315/126960788-5fef4049-3d60-477b-b414-0c0a392e0bd2.png)

### RIVM

App:
![RIVM iOS app](https://user-images.githubusercontent.com/1352315/126961744-a718a25d-4d0c-4736-9b61-f423fa3febb6.jpg)

Website:
![RIVM coronacheck.nl](https://user-images.githubusercontent.com/1352315/126961799-e8b6a591-0d08-413b-a540-0ce686aaa48e.png)

### QR in app

![IMG_1661](https://user-images.githubusercontent.com/1352315/126963251-3258de27-2073-4ebb-90d2-de95d44d192c.jpg)

**Desktop (please complete the following information):**
 - OS: Mac OS X 11.5
 - Browser: Chrome 92.0.4515.107

**Smartphone (please complete the following information):**
 - Device: iPhone7
 - OS: 14.7
 - Browser: Chrome 92.0.4515.90

### Additional context

Moved from #40 to a separate issue, since #40 got closed.

### Governance
- [x] I've read the contributing document https://github.com/minvws/.github/blob/master/CONTRIBUTING.md
- [x] I've read and understand the Code of Conduct https://github.com/minvws/.github/blob/master/CODE_OF_CONDUCT.md
- [x] I understand that any contributions or suggestions I made may make it into the actual code. I've read the License https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/LICENSE.txt and the contributor license agreement https://github.com/minvws/nl-covid19-notification-app-coordination/blob/master/CLA.md

**Comment by ijansch** [comment]
Thanks for the remarks. 

The 'is this the last dose: no' will be changed in the next release, as this is confusing. The line is only relevant when you receive only one Pfizer (because you previously had covid), and this indicates that you won't need a second.

As for the missing data in RIVM: IT's not actually missing, RIVM gives the app an 'hpkcode' from https://hpkcode.nl. When generating the certificate, you'll see that the missing data is enhanced from that json structure. However to avoid confusion, the next release will also look up the hpkcode in all of the apps and site, to populate those fields.

As for the 'identifier': the one in the 'wat is er opgehaald' should be sticky for your particular vaccination, so the same regardless of when/where you load it. The one that ends up in the eventual QR (the dcc certificate) is generated every time you create a new DCC. That is indeed intended behaviour. Should you notice the identifier from RIVM change between requests, feel free to log a separate issue for that.
